### ISSUE TITLE
Crop JSON

### ISSUE THREAD

**Issue by joshiejack** [joshiejack/Harvest-Festival#6]
@Yulife 
Crops need all their json created. I've already done a couple. 
They need a blockstate file like:
https://github.com/joshiejack/Harvest-Festival/blob/master/src/main/resources/assets/harvestfestival/blockstates/crops_block_cabbage.json

And then they need model files like
https://github.com/joshiejack/Harvest-Festival/blob/master/src/main/resources/assets/harvestfestival/models/block/cabbage_stage1.json
https://github.com/joshiejack/Harvest-Festival/blob/master/src/main/resources/assets/harvestfestival/models/block/cabbage_stage2.json
https://github.com/joshiejack/Harvest-Festival/blob/master/src/main/resources/assets/harvestfestival/models/block/cabbage_stage3.json
https://github.com/joshiejack/Harvest-Festival/blob/master/src/main/resources/assets/harvestfestival/models/block/cabbage_stage4.json

Each crop has a different number of stages. You can see the numbers from here:
https://github.com/joshiejack/Harvest-Festival/tree/master/src/main/java/joshie/harvest/crops/handlers

And here's the cabbage example
https://github.com/joshiejack/Harvest-Festival/blob/master/src/main/java/joshie/harvest/crops/handlers/StateHandlerCabbage.java#L7

Crops that need their json created are:
cucumber
strawberry
onion
corn
pineapple 
eggplant
spinach
sweet_potato 
green_pepper

**Comment by Yulife** [comment]
Oh ma lawd
